import { WorkflowTemplate } from "@/types";

// Pre-built workflow templates for common use cases
export const workflowTemplates: WorkflowTemplate[] = [
  {
    templateId: "content-pipeline",
    templateName: "Content Pipeline",
    templateDescription: "Complete content creation from idea to polished article",
    category: "Content Creation",
    icon: "📝",
    useCases: [
      "Blog post creation",
      "Article writing",
      "Content marketing",
    ],
    steps: [
      {
        stepNumber: 1,
        stepType: "prompt",
        platform: {
          id: "perplexity",
          name: "Perplexity AI",
          icon: "🔎",
          category: "AI Search",
          apiFormat: "json",
          maxTokens: 4000,
          description: "AI-powered search engine",
        },
        promptTemplate: "Research the topic: {topic}. Provide comprehensive information, key facts, and recent developments.",
        description: "Research phase - gather comprehensive information",
      },
      {
        stepNumber: 2,
        stepType: "prompt",
        platform: {
          id: "claude",
          name: "Claude (Anthropic)",
          icon: "🤖",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 200000,
          description: "Advanced AI model with long context window",
        },
        promptTemplate: "Based on this research:\n\n{previous}\n\nWrite a comprehensive first draft article about {topic}. Include an introduction, main points, and conclusion.",
        useOutputFromStep: 1,
        description: "Draft creation - write initial article",
      },
      {
        stepNumber: 3,
        stepType: "prompt",
        platform: {
          id: "chatgpt",
          name: "ChatGPT (OpenAI)",
          icon: "💬",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 128000,
          description: "Popular conversational AI model",
        },
        promptTemplate: "Polish and refine this draft:\n\n{previous}\n\nImprove clarity, fix grammar, enhance flow, and add engaging transitions. Make it publication-ready.",
        useOutputFromStep: 2,
        description: "Polish phase - refine and perfect",
      },
    ],
  },
  {
    templateId: "visual-story",
    templateName: "Visual Story Creator",
    templateDescription: "From concept to visual story across video and images",
    category: "Creative",
    icon: "🎬",
    useCases: [
      "Marketing videos",
      "Social media content",
      "Brand storytelling",
    ],
    steps: [
      {
        stepNumber: 1,
        stepType: "prompt",
        platform: {
          id: "claude",
          name: "Claude (Anthropic)",
          icon: "🤖",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 200000,
          description: "Advanced AI model with long context window",
        },
        promptTemplate: "Create a detailed video script for: {topic}. Include scene descriptions, dialogue, and visual directions. Format: Scene 1, Scene 2, etc.",
        description: "Script creation - detailed video storyboard",
      },
      {
        stepNumber: 2,
        stepType: "prompt",
        platform: {
          id: "midjourney",
          name: "Midjourney",
          icon: "🎨",
          category: "Image Generation",
          apiFormat: "text",
          maxTokens: 400,
          description: "High-quality AI image generation",
        },
        promptTemplate: "Create key frame image: {previous}\n\nExtract the most visually compelling scene and describe it in vivid detail for image generation.",
        useOutputFromStep: 1,
        transformationType: "extract",
        description: "Image generation - create key visual",
      },
      {
        stepNumber: 3,
        stepType: "prompt",
        platform: {
          id: "runway",
          name: "Runway",
          icon: "🎥",
          category: "Video Generation",
          apiFormat: "json",
          maxTokens: 1000,
          description: "Professional AI video tools",
        },
        promptTemplate: "Generate video from script:\n\n{step1}\n\nUsing key visual:\n\n{step2}\n\nCreate dynamic video with motion and transitions.",
        useOutputFromStep: 1,
        description: "Video generation - bring story to life",
      },
    ],
  },
  {
    templateId: "code-documentation",
    templateName: "Code Documentation Suite",
    templateDescription: "Complete code documentation from function to tests",
    category: "Development",
    icon: "⌨️",
    useCases: [
      "API documentation",
      "Code onboarding",
      "Developer handoff",
    ],
    steps: [
      {
        stepNumber: 1,
        stepType: "prompt",
        platform: {
          id: "chatgpt",
          name: "ChatGPT (OpenAI)",
          icon: "💬",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 128000,
          description: "Popular conversational AI model",
        },
        promptTemplate: "Analyze this code:\n\n{code}\n\nGenerate comprehensive documentation including: purpose, parameters, return values, exceptions, and usage examples.",
        description: "Documentation generation - create docs",
      },
      {
        stepNumber: 2,
        stepType: "prompt",
        platform: {
          id: "claude",
          name: "Claude (Anthropic)",
          icon: "🤖",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 200000,
          description: "Advanced AI model with long context window",
        },
        promptTemplate: "Based on this documentation:\n\n{previous}\n\nCreate 3-5 practical code examples showing different use cases and edge cases.",
        useOutputFromStep: 1,
        description: "Example creation - practical usage scenarios",
      },
      {
        stepNumber: 3,
        stepType: "prompt",
        platform: {
          id: "cursor",
          name: "Cursor",
          icon: "⌨️",
          category: "AI Code",
          apiFormat: "text",
          maxTokens: 8000,
          description: "AI code editor",
        },
        promptTemplate: "Generate comprehensive unit tests for:\n\nCode:\n{code}\n\nExamples:\n{previous}\n\nInclude edge cases, error handling, and mock data.",
        useOutputFromStep: 2,
        description: "Test generation - create unit tests",
      },
    ],
  },
  {
    templateId: "social-media-blast",
    templateName: "Social Media Blast",
    templateDescription: "Transform one idea into multi-platform social content",
    category: "Marketing",
    icon: "📱",
    useCases: [
      "Product launches",
      "Campaign announcements",
      "Multi-channel marketing",
    ],
    steps: [
      {
        stepNumber: 1,
        stepType: "prompt",
        platform: {
          id: "claude",
          name: "Claude (Anthropic)",
          icon: "🤖",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 200000,
          description: "Advanced AI model with long context window",
        },
        promptTemplate: "Create core message for: {topic}\n\nDefine key points, target audience, and main value proposition. Keep it clear and compelling.",
        description: "Core message - foundation for all content",
      },
      {
        stepNumber: 2,
        stepType: "prompt",
        platform: {
          id: "tweethunter",
          name: "TweetHunter",
          icon: "🐦",
          category: "Social Media AI",
          apiFormat: "text",
          maxTokens: 280,
          description: "AI Twitter content generator",
        },
        promptTemplate: "Create Twitter thread from:\n\n{previous}\n\nMake it engaging, use hooks, and stay within character limits. Include 5-7 tweets.",
        useOutputFromStep: 1,
        description: "Twitter content - engaging thread",
      },
      {
        stepNumber: 3,
        stepType: "prompt",
        platform: {
          id: "flick",
          name: "Flick",
          icon: "📸",
          category: "Social Media AI",
          apiFormat: "text",
          maxTokens: 2000,
          description: "Social media content planner",
        },
        promptTemplate: "Create Instagram caption from:\n\n{step1}\n\nInclude emojis, relevant hashtags, and call-to-action. Optimize for engagement.",
        useOutputFromStep: 1,
        description: "Instagram content - visual caption",
      },
    ],
  },
  {
    templateId: "research-to-presentation",
    templateName: "Research to Presentation",
    templateDescription: "Transform raw research into polished presentation",
    category: "Business",
    icon: "📊",
    useCases: [
      "Business presentations",
      "Investor pitches",
      "Team meetings",
    ],
    steps: [
      {
        stepNumber: 1,
        stepType: "prompt",
        platform: {
          id: "notebooklm",
          name: "NotebookLM",
          icon: "📓",
          category: "AI Research",
          apiFormat: "text",
          maxTokens: 100000,
          description: "AI research assistant by Google",
        },
        promptTemplate: "Analyze these research sources:\n\n{sources}\n\nExtract key findings, data points, and insights relevant to {topic}.",
        description: "Research analysis - extract insights",
      },
      {
        stepNumber: 2,
        stepType: "prompt",
        platform: {
          id: "claude",
          name: "Claude (Anthropic)",
          icon: "🤖",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 200000,
          description: "Advanced AI model with long context window",
        },
        promptTemplate: "Create presentation outline from:\n\n{previous}\n\nStructure: Executive Summary, Problem, Solution, Data, Conclusion. Include slide titles and key points.",
        useOutputFromStep: 1,
        description: "Outline creation - structure presentation",
      },
      {
        stepNumber: 3,
        stepType: "prompt",
        platform: {
          id: "gamma",
          name: "Gamma",
          icon: "📊",
          category: "Presentation AI",
          apiFormat: "text",
          maxTokens: 2000,
          description: "AI presentation builder",
        },
        promptTemplate: "Generate presentation slides from:\n\n{previous}\n\nCreate visually appealing slides with clear hierarchy, bullet points, and suggested visuals.",
        useOutputFromStep: 2,
        description: "Slide generation - build presentation",
      },
    ],
  },
  {
    templateId: "transcript-summary-social",
    templateName: "Transcript to Social Summary",
    templateDescription: "Transform meeting transcripts into shareable summaries",
    category: "Productivity",
    icon: "🎯",
    useCases: [
      "Meeting notes",
      "Podcast summaries",
      "Webinar recaps",
    ],
    steps: [
      {
        stepNumber: 1,
        stepType: "prompt",
        platform: {
          id: "fathom",
          name: "Fathom",
          icon: "🎯",
          category: "Meeting AI",
          apiFormat: "text",
          maxTokens: 5000,
          description: "AI meeting assistant",
        },
        promptTemplate: "Summarize this transcript:\n\n{transcript}\n\nExtract: key decisions, action items, important quotes, and main topics discussed.",
        description: "Transcript analysis - extract key information",
      },
      {
        stepNumber: 2,
        stepType: "prompt",
        platform: {
          id: "claude",
          name: "Claude (Anthropic)",
          icon: "🤖",
          category: "AI Chat",
          apiFormat: "json",
          maxTokens: 200000,
          description: "Advanced AI model with long context window",
        },
        promptTemplate: "Create executive summary from:\n\n{previous}\n\nFormat: 3-5 bullet points, each under 50 words. Focus on actionable insights and decisions.",
        useOutputFromStep: 1,
        transformationType: "summarize",
        description: "Summary creation - concise highlights",
      },
      {
        stepNumber: 3,
        stepType: "prompt",
        platform: {
          id: "buffer",
          name: "Buffer AI",
          icon: "📱",
          category: "Social Media AI",
          apiFormat: "text",
          maxTokens: 500,
          description: "AI social media assistant",
        },
        promptTemplate: "Create social media post from:\n\n{previous}\n\nMake it engaging and shareable. Include emoji and clear value proposition.",
        useOutputFromStep: 2,
        description: "Social content - shareable post",
      },
    ],
  },
];
