import { Platform } from "@/types";

export const platforms: Platform[] = [
  {
    id: "claude",
    name: "Claude (Anthropic)",
    icon: "🤖",
    category: "AI Chat",
    apiFormat: "json",
    maxTokens: 200000,
    specialRequirements: ["Prefers XML tags for structure", "Supports system prompts"],
    systemPromptTemplate: "You are a helpful AI assistant.",
    userPromptTemplate: "{prompt}",
    description: "Advanced AI model with long context window",
  },
  {
    id: "chatgpt",
    name: "ChatGPT (OpenAI)",
    icon: "💬",
    category: "AI Chat",
    apiFormat: "json",
    maxTokens: 128000,
    specialRequirements: ["Function calling support", "JSON mode available"],
    systemPromptTemplate: "You are a helpful assistant.",
    userPromptTemplate: "{prompt}",
    description: "Popular conversational AI model",
  },
  {
    id: "gemini",
    name: "Gemini (Google)",
    icon: "✨",
    category: "AI Chat",
    apiFormat: "json",
    maxTokens: 1000000,
    specialRequirements: ["Multimodal support", "Large context window"],
    systemPromptTemplate: "System instructions: {instructions}",
    userPromptTemplate: "{prompt}",
    description: "Google's multimodal AI model",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    icon: "🔍",
    category: "AI Chat",
    apiFormat: "json",
    maxTokens: 32000,
    specialRequirements: ["Optimized for reasoning tasks"],
    systemPromptTemplate: "You are DeepSeek AI assistant.",
    userPromptTemplate: "{prompt}",
    description: "Reasoning-focused AI model",
  },
  {
    id: "grok",
    name: "Grok (X.AI)",
    icon: "🚀",
    category: "AI Chat",
    apiFormat: "json",
    maxTokens: 25000,
    specialRequirements: ["Real-time data access", "Conversational style"],
    systemPromptTemplate: "You are Grok, a witty AI assistant.",
    userPromptTemplate: "{prompt}",
    description: "X.AI's conversational model",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    icon: "🎨",
    category: "Image Generation",
    apiFormat: "text",
    maxTokens: 400,
    specialRequirements: [
      "Use /imagine command",
      "Parameters with --",
      "Comma-separated descriptors",
      "Aspect ratio with --ar",
    ],
    userPromptTemplate: "/imagine {prompt} --ar 16:9 --v 6",
    description: "High-quality AI image generation",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    icon: "📐",
    category: "Image Generation",
    apiFormat: "text",
    maxTokens: 1000,
    specialRequirements: ["Good for text in images", "Style presets available"],
    userPromptTemplate: "{prompt}",
    description: "AI image gen with text rendering",
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    icon: "🖼️",
    category: "Image Generation",
    apiFormat: "json",
    maxTokens: 1000,
    specialRequirements: ["Model selection important", "Negative prompts supported"],
    userPromptTemplate: "{prompt}",
    description: "Versatile AI art generation",
  },
  {
    id: "glif",
    name: "Glif",
    icon: "⚡",
    category: "AI Workflow",
    apiFormat: "json",
    maxTokens: 2000,
    specialRequirements: ["Visual workflow builder", "Template-based"],
    userPromptTemplate: "{prompt}",
    description: "No-code AI workflow platform",
  },
  {
    id: "nanobana",
    name: "Nano Banana",
    icon: "🍌",
    category: "AI Workflow",
    apiFormat: "json",
    maxTokens: 4000,
    specialRequirements: ["Chained operations", "API composition"],
    userPromptTemplate: "{prompt}",
    description: "AI workflow automation tool",
  },
  {
    id: "kling",
    name: "Kling AI",
    icon: "🎬",
    category: "Video Generation",
    apiFormat: "text",
    maxTokens: 500,
    specialRequirements: ["Describe motion clearly", "Scene composition"],
    userPromptTemplate: "{prompt}",
    description: "AI video generation platform",
  },
  {
    id: "runway",
    name: "Runway",
    icon: "🎥",
    category: "Video Generation",
    apiFormat: "json",
    maxTokens: 1000,
    specialRequirements: ["Multiple video tools", "Gen-2 and Gen-3 models"],
    userPromptTemplate: "{prompt}",
    description: "Professional AI video tools",
  },
  {
    id: "pika",
    name: "Pika AI",
    icon: "📹",
    category: "Video Generation",
    apiFormat: "text",
    maxTokens: 500,
    specialRequirements: ["Image-to-video", "Text-to-video", "Parameters with -"],
    userPromptTemplate: "{prompt}",
    description: "Creative video generation AI",
  },
  {
    id: "luma",
    name: "Luma Dream Machine",
    icon: "💫",
    category: "Video Generation",
    apiFormat: "text",
    maxTokens: 800,
    specialRequirements: ["High-quality output", "Longer generations"],
    userPromptTemplate: "{prompt}",
    description: "High-fidelity AI video creator",
  },
  {
    id: "heygen",
    name: "HeyGen",
    icon: "👤",
    category: "Video Generation",
    apiFormat: "json",
    maxTokens: 3000,
    specialRequirements: ["Avatar-based", "Voice selection", "Script format"],
    userPromptTemplate: "{prompt}",
    description: "AI avatar video generation",
  },
  {
    id: "suno",
    name: "Suno",
    icon: "🎵",
    category: "Audio Generation",
    apiFormat: "text",
    maxTokens: 500,
    specialRequirements: ["Genre specification", "Lyrics optional", "Style tags"],
    userPromptTemplate: "{prompt}",
    description: "AI music generation platform",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    icon: "🎙️",
    category: "Audio Generation",
    apiFormat: "json",
    maxTokens: 5000,
    specialRequirements: ["Voice ID selection", "Stability settings"],
    userPromptTemplate: "{prompt}",
    description: "AI voice synthesis platform",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    icon: "🔎",
    category: "AI Search",
    apiFormat: "json",
    maxTokens: 4000,
    specialRequirements: ["Citation-focused", "Real-time search"],
    systemPromptTemplate: "Provide accurate, cited information.",
    userPromptTemplate: "{prompt}",
    description: "AI-powered search engine",
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    icon: "📓",
    category: "AI Research",
    apiFormat: "text",
    maxTokens: 100000,
    specialRequirements: ["Source-grounded", "Document analysis"],
    userPromptTemplate: "{prompt}",
    description: "AI research assistant by Google",
  },
  {
    id: "cursor",
    name: "Cursor",
    icon: "⌨️",
    category: "AI Code",
    apiFormat: "text",
    maxTokens: 8000,
    specialRequirements: ["Code context aware", "File references"],
    systemPromptTemplate: "You are an expert programmer.",
    userPromptTemplate: "{prompt}",
    description: "AI code editor",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    icon: "🤗",
    category: "AI Platform",
    apiFormat: "json",
    maxTokens: 4000,
    specialRequirements: ["Model-specific", "Inference API format"],
    userPromptTemplate: "{prompt}",
    description: "Open AI model platform",
  },
  {
    id: "canva",
    name: "Canva AI",
    icon: "🎨",
    category: "Design AI",
    apiFormat: "text",
    maxTokens: 500,
    specialRequirements: ["Design context", "Brand consistency"],
    userPromptTemplate: "{prompt}",
    description: "AI design assistant",
  },
  {
    id: "gamma",
    name: "Gamma",
    icon: "📊",
    category: "Presentation AI",
    apiFormat: "text",
    maxTokens: 2000,
    specialRequirements: ["Outline format helpful", "Slide structure"],
    userPromptTemplate: "{prompt}",
    description: "AI presentation builder",
  },
  {
    id: "notion",
    name: "Notion AI",
    icon: "📝",
    category: "Productivity AI",
    apiFormat: "text",
    maxTokens: 3000,
    specialRequirements: ["Context from workspace", "Action-oriented"],
    userPromptTemplate: "{prompt}",
    description: "AI writing assistant in Notion",
  },
  {
    id: "jasper",
    name: "Jasper",
    icon: "✍️",
    category: "Content AI",
    apiFormat: "json",
    maxTokens: 3000,
    specialRequirements: ["Marketing focus", "Brand voice"],
    userPromptTemplate: "{prompt}",
    description: "AI content generation platform",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    icon: "🎬",
    category: "Video AI",
    apiFormat: "json",
    maxTokens: 5000,
    specialRequirements: ["Avatar selection", "Script-based", "Language options"],
    userPromptTemplate: "{prompt}",
    description: "AI video creation with avatars",
  },
  {
    id: "descript",
    name: "Descript",
    icon: "🎬",
    category: "Video Editing AI",
    apiFormat: "text",
    maxTokens: 2000,
    specialRequirements: ["Transcription-based", "Edit as text"],
    userPromptTemplate: "{prompt}",
    description: "AI video and podcast editor",
  },
  {
    id: "removebg",
    name: "Remove.bg",
    icon: "🖼️",
    category: "Image Editing AI",
    apiFormat: "json",
    maxTokens: 200,
    specialRequirements: ["Image upload required", "Simple prompts"],
    userPromptTemplate: "{prompt}",
    description: "AI background removal",
  },
  {
    id: "capcut",
    name: "CapCut",
    icon: "✂️",
    category: "Video Editing AI",
    apiFormat: "text",
    maxTokens: 500,
    specialRequirements: ["Short-form focus", "Template-based"],
    userPromptTemplate: "{prompt}",
    description: "AI video editing tool",
  },
  {
    id: "make",
    name: "Make.com",
    icon: "🔧",
    category: "Automation",
    apiFormat: "json",
    maxTokens: 3000,
    specialRequirements: ["Scenario structure", "API integrations"],
    userPromptTemplate: "{prompt}",
    description: "Visual automation platform",
  },
  {
    id: "n8n",
    name: "n8n",
    icon: "🔄",
    category: "Automation",
    apiFormat: "json",
    maxTokens: 3000,
    specialRequirements: ["Node-based", "Self-hosted option"],
    userPromptTemplate: "{prompt}",
    description: "Workflow automation tool",
  },
  {
    id: "apify",
    name: "Apify",
    icon: "🕷️",
    category: "Data Extraction",
    apiFormat: "json",
    maxTokens: 2000,
    specialRequirements: ["Actor-based", "Web scraping focus"],
    userPromptTemplate: "{prompt}",
    description: "Web scraping and automation",
  },
  {
    id: "buffer",
    name: "Buffer AI",
    icon: "📱",
    category: "Social Media AI",
    apiFormat: "text",
    maxTokens: 500,
    specialRequirements: ["Platform-specific", "Engagement focus"],
    userPromptTemplate: "{prompt}",
    description: "AI social media assistant",
  },
  {
    id: "tweethunter",
    name: "TweetHunter",
    icon: "🐦",
    category: "Social Media AI",
    apiFormat: "text",
    maxTokens: 280,
    specialRequirements: ["Twitter format", "Thread structure"],
    userPromptTemplate: "{prompt}",
    description: "AI Twitter content generator",
  },
  {
    id: "hypefury",
    name: "Hypefury",
    icon: "🔥",
    category: "Social Media AI",
    apiFormat: "text",
    maxTokens: 300,
    specialRequirements: ["Engagement hooks", "Thread format"],
    userPromptTemplate: "{prompt}",
    description: "Twitter growth automation",
  },
  {
    id: "flick",
    name: "Flick",
    icon: "📸",
    category: "Social Media AI",
    apiFormat: "text",
    maxTokens: 2000,
    specialRequirements: ["Caption focus", "Hashtag strategy"],
    userPromptTemplate: "{prompt}",
    description: "Social media content planner",
  },
  {
    id: "opusclip",
    name: "Opus Clip",
    icon: "🎬",
    category: "Video AI",
    apiFormat: "text",
    maxTokens: 1000,
    specialRequirements: ["Long-form to short-form", "Viral clip detection"],
    userPromptTemplate: "{prompt}",
    description: "AI video clip generator",
  },
  {
    id: "fathom",
    name: "Fathom",
    icon: "🎯",
    category: "Meeting AI",
    apiFormat: "text",
    maxTokens: 5000,
    specialRequirements: ["Meeting transcription", "Summary format"],
    userPromptTemplate: "{prompt}",
    description: "AI meeting assistant",
  },
  {
    id: "typeform",
    name: "Typeform AI",
    icon: "📋",
    category: "Forms AI",
    apiFormat: "json",
    maxTokens: 1000,
    specialRequirements: ["Form logic", "Question flow"],
    userPromptTemplate: "{prompt}",
    description: "AI-powered form builder",
  },
];

export const getPlatformById = (id: string): Platform | undefined => {
  return platforms.find((p) => p.id === id);
};

export const getPlatformsByCategory = (category: string): Platform[] => {
  return platforms.filter((p) => p.category === category);
};

export const getAllCategories = (): string[] => {
  return Array.from(new Set(platforms.map((p) => p.category)));
};
